name: Create release package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: spec/windows/FlexLMConverter.spec

    - uses: actions/upload-artifact@v2
      with:
        name: main
        path: src/license_converter/dist/windows